### ISSUE TITLE
invalid integer

### ISSUE THREAD

**Issue by alessandrodimarco** [fisherman/mono#3]
I am receiving the error `test returned eval errors: 	invalid integer ''`. The variable $CMD_DURATION has been renamed $cmd_duration [fish 4414](https://github.com/fish-shell/fish-shell/issues/4414).

**Comment by alessandrodimarco** [comment]
Turns out its `humanize_duration` that hasn't renamed the variable. I saw the readme had `$CMD_DURATION` but the code is correct.

**Comment by onbjerg** [comment]
What was the fix?
