### ISSUE TITLE
"Invalid integer" error

### ISSUE THREAD

**Issue by paper-lark** [fisherman/mono#4]
After successful installation using Fisherman I'm getting the following error whenever I try to execute any command:

```
test returned eval errors:
	invalid integer ''
```

**Comment by JorgeBucaran** [comment]
Maybe the error is that in the newest version of fish-shell the CMD_DURATION was renamed to cmd_duration.

**Comment by paper-lark** [comment]
I'm using fish shell, version 2.7.1, installed via brew.

**Comment by JorgeBucaran** [comment]
@paper-lark Is this a fisherman issue or mono issue? 🤔

**Comment by paper-lark** [comment]
How can I find that out?

**Comment by JorgeBucaran** [comment]
Don't worry, you did fine. I'll try to help later when I have a bit more time. I suggest you try another theme and if the problem persists, then open an issue in the fisherman/fisherman repo.

**Comment by paper-lark** [comment]
Okay, thank you!

**Comment by paper-lark** [comment]
@JorgeBucaran I tried to investigate the issue. Running the shell in debug mode I got the following output:

```bash
<3> fish: proc::read_try('test ! -z "$status_code"')
<5> fish: intern /Users/paper-lark/.config/fish/functions/fish_right_prompt.fish
<5> fish: universal log sync
<5> fish: universal log sync elided based on fast stat()
<5> fish: universal log no modifications
<4> fish: Exec job 'test "$cmd_duration" -gt 250' with id 2
<2> fish: Fork #18, pid 7555: internal builtin for 'test'
<3> fish: Job is constructed
<4> fish: Continue job 2, gid 7537 (test "$cmd_duration" -gt 250), UNCOMPLETED, NON-INTERACTIVE
<3> fish: select_try on 3
test returned eval errors:
	invalid integer ''
```
I'm new to Fish Shell and I might be wrong but apparently the problem is in call to `proc::read_try`, maybe there should be `$status` instead of `$status_code`, and it seems to be an issue in Fish Shell itself since the function is told to be derived from there.

**Comment by mhubig** [comment]
same problem here after i installed with fisherman ...

**Comment by jorgebucaran** [comment]
@paper-lark @mhubig I finally upgraded to 2.7.1 and got no issues with this theme.

**Comment by paper-lark** [comment]
Sadly, I seem to still have the same issue.

**Comment by jorgebucaran** [comment]
@paper-lark I can't repro. Please check this is not actually a problem with your fish configuration, a different plugin or something else.

**Comment by paper-lark** [comment]
I don't think I have anything else installed. Could you give me some hints on how I can investigate the cause of the problem?

**Comment by jorgebucaran** [comment]
@paper-lark Well, first uninstall this theme to see if the problem persists, so that we know if the problem is only this theme or something else.

**Comment by paper-lark** [comment]
There are no issues once the theme is uninstalled. However, as soon as I install it I get the same message as I did before. Updating does not change anything, so I assume I have the latest version of the prompt.

**Comment by mhubig** [comment]
Here is the way I can reproduce the error. I started with a freshly installed fish 2.7.1.

I removed any configuration:
```fish
$ mv .config/fish/ .config/fish-bak
```
Here I restarted iTerm.
```fish
$ curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
...
$ fisher mono
Installing 1 plugin/s
OK Copy mono
Installing 6 dependencies
OK Copy git_util
OK Copy pwd_is_home
OK Copy pwd_info
OK Copy host_info
OK Copy last_job_id
OK Copy humanize_duration
Done in 628ms
test returned eval errors:
	invalid integer ''
```
From now on, every time I press enter I get the same error:

```fish
~
test returned eval errors:
	invalid integer ''
```
Now I remove mono and the error is gone:

```fish
~ fisher rm mono
Done in 362ms
```

**Comment by jorgebucaran** [comment]
@paper-lark Great, now we know the issue is with this theme! Good job! Now let me have a look at the code again.

**Comment by jorgebucaran** [comment]
Well, we also need to look into the plugins in https://github.com/fisherman/mono/blob/master/fishfile. Maybe the error is there.

I am still surprised I can't repro it.

**Comment by jorgebucaran** [comment]
I'm on macOS High Sierra (10.13.3) btw.

**Comment by mhubig** [comment]
I'm also on macOS High Sierra (10.13.3) ...

**Comment by jorgebucaran** [comment]
@paper-lark @mhubig What about a different theme? Try `boss`, which is the one I use myself.

**Comment by mhubig** [comment]
I have hulk. Works like a charm ...

**Comment by jorgebucaran** [comment]
@mhubig Hulk doesn't use a fishfile / doesn't have any dependencies so it may not be the best example to try here. Try another one. 🙏

**Comment by mhubig** [comment]
Tryed `boss` no problem:

```fish
$ fisher rm hulk
$ fisher boss
# boss works
$ fisher rm boss
$ fisher hulk
# hulk works
```

**Comment by jorgebucaran** [comment]
Alright, so maybe there's a bug in any of these:

- fisherman/pwd_is_home
- fisherman/pwd_info
- fisherman/host_info

**Comment by mhubig** [comment]
Is it sufficient to just call those commands to test?

**Comment by jorgebucaran** [comment]
That's a way to start, yes, try that first.

**Comment by mhubig** [comment]
OK I tried those commands but couldn’t recreate the errors ...

**Comment by msikma** [comment]
Just wanted to confirm that I had the same error, but manually editing in the fix from #5 made it work again. This is with a new Fish, new Fisherman and OSX 10.13.5.

**Comment by jorgebucaran** [comment]
A backward compatible solution is explained here: https://github.com/fisherman/mono/pull/5#issuecomment-374655713

@mhubig Could you send us a PR? :)

**Comment by mhubig** [comment]
@jorgebucaran It's right here https://github.com/fisherman/mono/pull/5 waiting 👀
